[program:laravel-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /app/artisan queue:work --verbose --tries=3 --timeout=90 --sleep=3 --max-jobs=1000
autostart=true
autorestart=true
numprocs=2
user=root
redirect_stderr=true
stdout_logfile=/app/storage/logs/worker.log
